[package]
name = "rrplug"
version = "4.0.0"
authors = ["catornot"]
description = "wrappers and functions for R2Northstar plugins"
repository = "https://github.com/catornot/rrplug"
license = "Apache-2.0 OR MIT"
keywords = ["plugin", "northstar", "titanfall"]
exclude  = ["/rrplug_template", ".gitignore"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.40"
log = "0.4.19"
once_cell = "1.18.0"
rrplug_proc = { path = "./rrplug_proc" }
parking_lot = "0.12.1"

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
targets = ["x86_64-pc-windows-msvc"]

[features]
default = []
async_engine = []
